target-version = 'py312'
line-length = 100

[format]
quote-style = 'preserve'

[lint]
extend-select = [
    'A', # flake8-builtins
    'ARG', # flake8-unused-arguments
    'B', # flake8-bugbear
    'C4', # flake8-comprehensions
    'COM', # flake8-commas
    'DTZ', # flake8-datetimez
    'E', # pycodestyle
    'EM', # flake8-errmsg
    'F', # pyflakes
    'FURB', # refurb
    'I', # isort
    'N', # pep8-naming
    'PERF', # perflint
    'PIE', # flake8-pie
    'PL', # pylint
    'PTH', # flake8-use-pathlib
    'RET', # flake8-return
    'RUF', # ruff
    'S', # flake8-bandit
    'SIM', # flake8-simplify
    'SLF', # flake8-self
    'TC', # flake8-type-checking
    'TRY', # tryceratops
    'UP', # pyupgrade
    'W', # pycodestyle
]
ignore = [
    'missing-trailing-comma', # use is discouraged when using the formatter
    'line-too-long',
    'too-many-return-statements',
    'too-many-branches',
    'too-many-arguments',
    'too-many-locals',
    'too-many-statements',
    'too-many-positional-arguments',
    'magic-value-comparison',
    'suspicious-subprocess-import',
    'subprocess-without-shell-equals-true',
    'start-process-with-partial-path',
]
preview = true
