name: Lint checks
on: [push, pull_request, workflow_dispatch]
enable-email-notifications: true
jobs:
  fish:
    uses: nathanchance/actions-workflows/.forgejo/workflows/fish_format.yml@main
  python:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.15', '3.14', '3.13', '3.12']
    uses: nathanchance/actions-workflows/.forgejo/workflows/python_lint.yml@main
    with:
      python_version: ${{ matrix.version }}
