name: Lint checks
on: [push, pull_request]
jobs:
  fish:
    uses: nathanchance/actions-workflows/.github/workflows/fish_format.yml@main
  python:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.13', '3.12', '3.11', '3.10', '3.9', '3.8']
    uses: nathanchance/actions-workflows/.github/workflows/python_lint.yml@main
    with:
      python_version: ${{ matrix.version }}
