name: Lint checks
on: [push, pull_request]
jobs:
  fish:
    uses: nathanchance/actions-workflows/.github/workflows/fish_format.yml@main
  yapf:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/yapf.yml@main
